### ISSUE TITLE
LineageOS for microG 17.1

### ISSUE THREAD

**Issue by ghost** [microg/GmsCore#1063]
How come there are no LineageOS for microG 17.1 builds, while the website states

> We ship OTA updates from upstream LineageOS weekly. In this way you always receive new features and security updates just few days after they are released mainline.

I thought this was an automated process?

**Comment by TheLastGimbus** [comment]
I've read that the guy who runs Lineage for microG is copletley different guy, and for now, he's doing something else, and he's known for that kind of "floating between multiple projects".
Kinda sucks, open source shouldn't look like this :/

**Comment by ArchangeGabriel** [comment]
@TheLastGimbus You’re mixing things. The person you describe is @mar-v-in, who develops microG. However @corna, who handles Lineage for microG, is indeed a completely different guy.

@m54fjt6910tt3o948b1zi840oanas5uty4j3nq2 See https://github.com/lineageos4microg/docker-lineage-cicd/pull/70. But as said above, @corna is not answering anymore regarding this project, so…

**Comment by m54fjt6910tt3o948b1zi840oanas5uty4j3nq2** [comment]
@ArchangeGabriel Thanks. I wasn't aware of the PR. Let's hope somebody will take over the project.

**Comment by ArchangeGabriel** [comment]
@m54fjt6910tt3o948b1zi840oanas5uty4j3nq2 For what it’s worth, I got an answer from @corna, he is currently overly busy, but still hopes to return to the project at some point or at least find someone to take it over. But it could be some times before that happens.

**Comment by spolack** [comment]
I plan to give the docker build image a refresh, but for me it was still not clear if its worth it, as microg development has been stalled for quite some time and there are a few glitches with LOS 17 and current Apps.. There were also open questions on, whether we might want to use microg fork from e.foundation, which seems to be currently better maintained.

**Comment by m54fjt6910tt3o948b1zi840oanas5uty4j3nq2** [comment]
@spolack It'll definitely be worth it, especially since @mar-v-in resumed development lately: https://gist.github.com/mar-v-in/c8254168c63361c5094de13a7afea344#gistcomment-3311911

**Comment by h4ndi** [comment]
May you have a look here: https://www.reddit.com/r/MicroG/comments/h8cwpg/i_created_a_tool_to_build_los_171_with_signature/
or here: https://gitlab.com/fremontt/minimal-docker-for-lineageos/image

I had to change a few things, because the final zip signing always failed for me:
- In the Dockerfile add python2 to the packages to be installed.
- In `utils/run.sh` I'm pointing `/usr/bin/python` to `python2`
`rm /usr/bin/python`
`ln /usr/bin/python2 /usr/bin/python`
- In `utils/build-los.sh` in function `syncSources` I added a `--force-sync` to fix some syncing problems.

I'm using the restricted sigspoof patch and installed [Magisk](https://github.com/topjohnwu/Magisk/releases) and [MinMicroG (NoGoolage)](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases) via Magisk.

**Comment by m54fjt6910tt3o948b1zi840oanas5uty4j3nq2** [comment]
It's great to see the 17.1 builds being released - thank you everyone!

I think this issue can be closed now :-)

However, I'd like to mention: https://github.com/lineageos4microg/l4m_website/issues/52
