### ISSUE TITLE
QR venue check-in unavailiable [GMS Vision API]

### ISSUE THREAD

**Issue by JonnyTech** [microg/GmsCore#1297]
The UK NHS Covid-19 app does not allow me to use the QR code scanning facility for venue check-in.

Tested on devices running Android 9, 10 and 11.

Is this because of a limitation in microG?

![img_38](https://user-images.githubusercontent.com/3584732/100819359-ebe46880-3443-11eb-9560-64d02adff40d.jpg)
![Imagepipe_0](https://user-images.githubusercontent.com/3584732/100819374-f1da4980-3443-11eb-9cc6-f3bd04f2c8e9.jpg)

**Comment by Romern** [comment]
The Google GMS Vision API ( https://developers.google.com/android/reference/com/google/android/gms/vision/Detector ) is not implemented, which is used for the QR venue check-in ( https://github.com/nhsx/covid-19-app-android-ag-public/blob/master/app/src/main/java/uk/nhs/nhsx/covid19/android/app/qrcode/QrScannerActivity.kt ). Related Issues: https://github.com/microg/GmsCore/issues/1211, https://github.com/microg/GmsCore/issues/670, https://github.com/microg/GmsCore/issues/395 .

**Comment by JonnyTech** [comment]
Thanks @Romern - hopefully it is on @mar-v-in's roadmap.

**Comment by mar-v-in** [comment]
Vision Barcode API is now added via 5e39818a20032d261215420fc72e05efad4202b5.

**Comment by JonnyTech** [comment]
Thank you very much @mar-v-in and @lfxgroove.

**Comment by edenist** [comment]
Thanks for your work so far on this! 

I would like to add that the vision api still appears to be failing with the "Service Victoria" check-in app. 
https://play.google.com/store/apps/details?id=au.gov.vic.service.digitalwallet.citizen

Here's a logcat output when trying to take a photo of the QR code. https://pastebin.com/FNy8K5v3

It appears to find the new vision api modules, but then the following suggests the app might be using it in an unexpected way?

`05-21 11:31:45.615 D/SafeParcel(10335): Unknown field id 3 in com.google.android.gms.vision.barcode.internal.client.BarcodeDetectorOptions, skipping.`

Figured I would add this here rather than opening up a new issue.

**Comment by edenist** [comment]
Just posting that the problem I mentioned above no longer seems to be an issue. The check-in application was updated and now works, so the errors above were likely just red herrings and the issue was within the app itself. 
Sorry about the noise!

**Comment by projectgus** [comment]
@edenist FWIW, I thought the Service Vic app didn't work for a long time because of #1536. A workaround is to zoom out so the QR code is relatively small in the centre of the live camera display, and then the app scans it OK. If you zoom in "correctly" so the QR code fills the region marked on the live camera display then the app thinks it is out of bounds and it doesn't scan. It's possible this region check has been totally removed in an app update as well, though.
