### ISSUE TITLE
[EN] Error in Corona-Warn-App after update to 1.9.1 - URSACHE: 9002 - ClassNotFoundException

### ISSUE THREAD

**Issue by Diapolo** [microg/GmsCore#1325]
## Technical details

- Device name: Fairphone 2
- Android version: Android 10 / LineageOS for microG ([lineage-17.1-20201203-microG-FP2.zip](https://download.lineage.microg.org/FP2/lineage-17.1-20201203-microG-FP2.zip))
- App version: 1.9.1
- ENF version: 204713000
- microG version: [v0.2.15.204713](https://github.com/microg/GmsCore/releases/tag/v0.2.15.204713)

## Describe the bug

I initially got the error **URSACHE: 9002 - ClassNotFoundException** today after upgrading from 1.7.1 to 1.9.1 right after opening CWA the first time during **Prüfung läuft...**. I didn't bother, but saw that my last update state in the app was stuck at yesterday 16:24 or something.

Today I tried to reset the app and got the same error at the same step **Prüfung läuft...**. After a few minutes I get the expected screen after a reset.

![CWA 9002 - 01](https://user-images.githubusercontent.com/1419649/102697674-e787c000-4237-11eb-915f-9f7b32b80691.jpg)

## Detailed screenshots

![Screenshot_20201219-202711_Corona-Warn](https://user-images.githubusercontent.com/1419649/102697814-12bedf00-4239-11eb-8497-155baa553a34.png)
![Screenshot_20201219-202724_Corona-Warn](https://user-images.githubusercontent.com/1419649/102697820-1e120a80-4239-11eb-94c3-54072e4c6a3b.png)
![Screenshot_20201219-202733_Corona-Warn](https://user-images.githubusercontent.com/1419649/102697821-20746480-4239-11eb-821c-97ebcd35f913.png)

## Steps to reproduce the issue

1. Reset the app and activate Risikoermittlung
2. **Daten werden herungergeladen...** is working
3. Error shows up in the **Prüfung läuft...** step

## Additional information

Exposure notification details (microG) is showing me that I got key updates right after resetting.
Also see: corona-warn-app/cwa-app-android#1960

**Comment by fuelflo** [comment]
I'm having the same issue since the update to CWA 1.9.1.

**Comment by YtvwlD** [comment]
The changelog for CWA 1.9.1 includes the usage of version 2.0 of the Exposure Notification API.

**Comment by mar-v-in** [comment]
[ExposureStateUpdateReceiver.kt#L54-L56](https://github.com/corona-warn-app/cwa-app-android/blob/49996ef/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/receiver/ExposureStateUpdateReceiver.kt#L54-L56) triggers v1 mode deserialization as [EXTRA_TOKEN](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient#public-static-final-string-extra_token) is not supported in ExposureWindow mode. In v1 mode, the intent contains [EXTRA_EXPOSURE_SUMMARY](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient#public-static-final-string-extra_exposure_summary) which is of type [ExposureSummary](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureSummary). ExposureSummary is part of the Play Service client library. However, as CWA doesn't need it (because it doesn't use v1 mode), ProGuard removes it from the release build, resulting in the ClassNotFoundException.

Of course we can work-around this from microG, as apparently Google Play Services also can handle this.

Building debug version of CWA from source should work fine, as those are not ProGuard-optimized.
CCTG 1.9 also works as expected. You can get its latest preview from https://bubu1.eu/cctg/

**Comment by Diapolo** [comment]
@mar-v-in It would be very nice if you could work-around that behaviour. I opened a ticket in the official CWA repo and they pointed me here as I'm using microG.

I'd be glad to help test a microG version with a fix for this... thanks for diggin in!

**Comment by mar-v-in** [comment]
> By the way, when using CCTG 1.9 and having microG installed, is the CCTG 1.9 bundled ENF lib used or the external microG one?

CCTG uses microG service if installed and only falls back to bundled microG EN implementation if not.

**Comment by mar-v-in** [comment]
Please try with build from https://microg.org/dl/core-nightly.apk
Note that it may take a few hours for CWA to update risk calculation.

**Comment by fuelflo** [comment]
For me the nightly seems to work, the CWA is not stuck anymore with last update from 1,5 days ago and until now I didn't get another error message.

Let's see if it's the same for @Diapolo ...

**Comment by Diapolo** [comment]
Yes the error has gone, great work!

One thing I observed is that after I installed the new microG version and reset the CWA yesterday 21:47, this morning after booting the phone and CWA showing me **"Prüfung läuft..."**, I still get shown "Aktualisiert: Gestern, 21:47", which seems wrong?

**Comment by real-or-random** [comment]
I can confirm that the issues is gone.

**Comment by nidico** [comment]
I can confirm this issue does not occur with CWA 1.9.1 on microg GmsCore v0.2.16.204713 (released today).
