### ISSUE TITLE
[Feature request] Support import of exposure.db  without root

### ISSUE THREAD

**Issue by corneliusroemer** [microg/GmsCore#1328]
It would be nice if MicroG supported an import of the exposure.db - now that the export is possible.

There are a couple of reasons when such an import function would be helpful:
- switching phones
- adding keys back after app crash/data corruption
- joining the exposure data from two phones for combined risk calculation (e.g. work phone and private phone)

There's already an import/export issue #1208 but export is solved now and the first comments of said issue are more of a discussion of the CWA than MicroG. Thus, I thought it would be beneficial to start a dedicated thread.

@tlambertz implemented the export - once export works, import shouldn't be too hard!

>I've just filed a pull request which allows you to export the database from microg (#1291). You could then check the keys with the corona companion app, once [corona-warn-companion#97](https://github.com/mh-/corona-warn-companion-android/pull/97) is implemented. This is not exactly the same as a re-import, but should give similar (in my opinion even better) results.
_Originally posted by @tlambertz in https://github.com/microg/GmsCore/issues/1208#issuecomment-735468880_

Implementation shouldn't be too hard. Could be based mostly on above PR. The trickiest bit should be to sanitize import db, combine import with old db and make sure nothing breaks now that the database has changed. See https://github.com/microg/GmsCore/pull/1291/files

**Comment by tlambertz** [comment]
As it is implemented now, only the received codes are exported and not the send ones. Together with the companion-app this gives you the ability to check whether you have been in contact, but you will not be able to notify others should you get infected. (But when switching phones even this might be tricky, since the companion has no "open from file" currently, just a receiver for the custom MicroG intent.)

I have not looked at the database format yet, but import is often more tricky than export, since you might have to join two databases. What happens when the imported DB is of a different version?
MicroG has code to update one database version to a newer one. It might be easiest to delete the existing DB, and then use the upgrade code on the imported DB.

**Comment by corneliusroemer** [comment]
Hmm, I see. I knew that the broadcast keys are not exported in exposure.db ;) No "open from file" is a good point, best addressed over at https://github.com/mh-/corona-warn-companion-android/issues, I'll open an issue there.

Yes, import may well be trickier. For version mismatch, if the upgrade function is general, one could upgrade the imported DB separately, then merge the databases. Starting point could be to replace existing one with imported one, that would help with import and most use cases. Merging is a less important feature.

**Comment by mar-v-in** [comment]
b7717e5d92f71889dac076f7bd4c71fe8a44f53c adds support for backups using adb backup/restore or seedvault. Backups will also cover `exposure.db`.

**Comment by corneliusroemer** [comment]
@mar-v-in Thanks, that was quick :) If someone wants to test on a spare phone, please report back here.

If I understand it correctly, data gets now backed up automatically roughly once a day. If you install the app on a new phone, the backup is used to populate app data, thus restoring from the most recent checkpoint. Bit more detail here: https://developer.android.com/guide/topics/data/autobackup (for Android 9+, 8- uses a different backup system).
