### ISSUE TITLE
SharedPreferences seem to clear each other

### ISSUE THREAD

**Issue by Uldiniad** [microg/GmsCore#1433]
**To Reproduce**
1. Go to microG settings
2. Click on Cloud Messaging
3. Observe shared preferences state
4. Go back and click on Google device registration
5. Observe shared preferences state

**Expected behavior**
SharedPreferences should likely not be clearing eachother?

**System**
Android Version: 11
Custom ROM: CalyxOS

**Additional context**
```
First boot
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <long name="exposure_last_cleanup" value="1617212642622" />
</map>

Open GCM
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="gcm_network_mobile">0</string>
    <string name="gcm_network_roaming">0</string>
    <string name="gcm_network_wifi">0</string>
    <long name="exposure_last_cleanup" value="1617212642622" />
    <boolean name="gcm_enable_mcs_service" value="true" />
    <boolean name="gcm_confirm_new_apps" value="false" />
    <string name="gcm_network_other">0</string>
</map>

Open device registration
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="checkin_enable_service" value="true" />
</map>
```

**Comment by grote** [comment]
I can't reproduce this on current master.

However, it could be caused by the fact that Settings are being set from different processes via `ServiceInfoReceiver`s and  [`.gcm.ServiceInfoReceiver` is running in a different process than the others](https://github.com/microg/GmsCore/blob/a830b5dd5de71fa53f9d037c210a81fb38ea3321/play-services-core/src/main/AndroidManifest.xml#L259-L260). In `ProvisionService` for example, [broadcasts get fired to update settings in three receivers](https://github.com/microg/GmsCore/blob/e9766db28e312be701cb0c86c68917196b8571b1/play-services-core/src/main/kotlin/org/microg/gms/provision/ProvisionService.kt#L35-L37) where one could overwrite the others.
