### ISSUE TITLE
Apps not registering with GCM

### ISSUE THREAD

**Issue by ShubhamPatilsd** [microg/GmsCore#1533]
**Describe the bug**
So certain apps won't register with GCM. GCM is active and all check marks are ticked in "Self Check"

**To Reproduce**
1. Install GMSCore and GSFProxy
2. Register device with Google
3. Turn on GCM
4. No apps register even after relaunching them

**Expected behavior**
Apps should register with GCM automatically without me having to uninstall them/wipe their data 

**Screenshots**
![image](https://user-images.githubusercontent.com/55328098/129635982-fb719da9-8ac8-46d3-be98-cbf1ab234867.png)

**System**
Android Version: 11
Custom ROM: LineageOS 18.1

**Additional Info**
Google device registration is successful and GCM is NOT disconnected

**Comment by nift4** [comment]
> Apps should register with GCM automatically without me having to uninstall them/wipe their data

That's app side as far as I know.

**Comment by ShubhamPatilsd** [comment]
I see. So has this been a known problem for some time?

**Comment by nift4** [comment]
> I see. So has this been a known problem for some time?

Yep. Complain at Google, it's their fault

> Also, apps used to register automatically when i installed microG a couple weeks ago. Since I ran into issues with location based apps, I decided to use the nift4 microG installer revived and i believe this problem has originated since then.

No that's because due to the installation via my installer reseted microG and all apps have to reregister.

**Comment by ShubhamPatilsd** [comment]
So my only option is to re-install/wipe each app's data to reregister them?

**Comment by chris42** [comment]
A few apps have a button to register, like Threema, but otherwise yes. Make sure to backup your data within the apps, e.g., Whatsapp you can reinstall and use the built in backup and the registration will be fine.

**Comment by ShubhamPatilsd** [comment]
> ... Whatsapp you can reinstall and use the built in backup and the registration will be fine.

How would I do this if I'm signed in with Google and want a local backup. (I know this isnt a microG question but im struggling with this)

**Comment by chris42** [comment]
Regarding Whatsapp: Settings for backup are in Settings -> Chats -> Chat-Backup. There you should be able to configure backup and trigger the local backup (backup ends up on storage in Android/media/com.whatsapp/WhatsApp/Backups). Never tried the google backup and if a save/restore with microg will actually work. Local one works fine in microg.
Make sure to copy the WhatsApp folder in com.whatsapp off the device before deleting all data / uninstalling whatsapp. Since Whatsapp moved the file storage there, the backup will possibly be erased when uninstalling.
To restore, copy back the folder into the same structure, then install whatsapp. It should then offer you to restore the backup on initial opening.

**Comment by ShubhamPatilsd** [comment]
Ok thanks. I think I messed it up and I've tried so many times that I have to wait a couple more hours before Whatsapp will allow me to setup my account again.

**Comment by abda11ah** [comment]
You should also know that some mobile operators that only allow access to facebook/whatsapp/social websites for some of their subscriptions (in Morocco for example: the mobile operator "inwi" when use of a "*6" recharge number) are unable to connect to the Google FCM notification server, because their 4G subscription only allows the connection to whatsapp and facebook servers (not Google ones). You should use a full-internet suscription to make the Google FCM registration work.
