### ISSUE TITLE
After update, Google Device Registration self-enables

### ISSUE THREAD

**Issue by IzzySoft** [microg/GmsCore#1554]
**Describe the bug**
For good reasons, I have Google Device Registration turned off. That's also the default with microG as I understand. Still, at least on one of my devices, I've noticed multiple times now that updating microG leads to device registration being turned on. This regularly seems to happen with my Wileyfox Swift (crackling) running Oreo – but interestingly not on my BQ Aquaris X5 Plus (gohan) running Nougat (no newer Android available there).

**To Reproduce**
1. Update via the microG F-Droid repo (using the official F-Droid client)
2. Open the app
3. See device registration is turned on

**Expected behavior**
Device registration stays off.

**System**
Android Version: 8
Custom ROM: LineageOS 16

**Additional context**
I'd wish enabling that would require a PIN so it cannot happen accidentally.

**Comment by ale5000-git** [comment]
There was issues with settings being overriden fixed recently, so it is possibly already fixed.
So please test the update from v0.2.22.212658 to the new version when it will be released to see if it is still happens.

**Comment by IzzySoft** [comment]
That's great to read! And yes, I'll of course keep an eye on it. Though it might take a few updates without the toggle being flipped before we can be sure I guess :smile:

**Comment by IzzySoft** [comment]
Didn't see it anymore for a while, so this seems to be fixed. Feel free to close the issue unless you want to wait for more input (e.g. from where I just linked this).

**Comment by DJCrashdummy** [comment]
@IzzySoft thanks for pointing me at this issue.

- - -

i assume the same issue is applicable to *"LineageOS for microG"* because i also noticed it being on by default at least on some most recent 17.1 builds (build date 2021-10-10 or perhaps even newer ones).
unfortunately i don't have a flashable device by me right now to verify, but i'm pretty sure i also saw it enabled by default at some 18.1 builds (build date 2022-02-19).
btw: i'm not talking about only one particular device, but a few different ones (all Samsung, if that's of relevance).

**Comment by IzzySoft** [comment]
> i assume this issue is also applicable to "LineageOS for microG"

Confirmed, as that's where I had that issue. It was solved by updates from microG (via their F-Droid repo, no device flashing required). So as the problem is solved for me and didn't re-occur for more than one update now, I'll close this issue. Thanks for fixing, whoever did it :smiley:
