### ISSUE TITLE
GCM keeps disconnected from time to time (HUAWEI P SMART 2021)

### ISSUE THREAD

**Issue by mire777** [microg/GmsCore#1668]
**Describe the bug**
GCM messages works fine, but after few hours (around 6 hours) it shows "disconnected", and then i don't receive notifications. It will work again if I go to settings and toggle "Receive push notifications" - on/off. It seems that this happen in phone idle state only.. 

**To Reproduce**
No steps to reproduce, it happens spontaneously.. 

**Expected behavior**
GCM should keep connection all the time.. 

**System**
Android Version: 10
Custom ROM: EMUI 10.1.1
Model: PPA-LX2

**Additional context**
Huawei P Smart 2021

_______________________

**My steps**
In an attempt to resolve the problem.. 

1)All permisions are granted. 
2)I tryed all posible settings in MicroG, nothing worked.. 
3)I tryed ##2432546## trick, it doesnt work.. 
4) I double checked that app is running fine, and that nothing kills GCM. 

**Observations**
What i noticed.. 

In battery optimizations MicroG app doesn't appear at all, so i can't alow or restrict what MicroG doing in backgorund.. Also battery optimizations app ask me to uninstall MicroG because google play services is not compatible with the phone.. 

I can confirm, that in "launch records", MicroG was sometimes "alowed" to "auto launch", and sometimes is "restricted". Also if other app launch MicroG, this is "alowed". 

Any help would be appreciated, if this is not bug and can't be fixed in app, what can i do more? 

Thanks.

![Screenshot_20220210_111649](https://user-images.githubusercontent.com/3661484/153392638-6f0316a3-5d10-43e5-8510-39985e188e6b.jpg)

**Comment by pkcheng** [comment]
This is caused by a feature in Huawei's device called **Power Genie**. It basically kill those application running in the background periodically to save battery life. They put a series of apps like Facebook, WeChat in the white list so that these apps will not be killed but MicroG is not in the list. There is no way to manually add an app to that list so far.

To solve your issue, you could uninstall the Power Genie on your Huawei P Smart. ([https://www.youtube.com/watch?v=2tfZmxqEnz4](url))

Don't worry about uninstalling this, I did that 6 months ago, it doesn't bring me any negative effects.

**Comment by mire777** [comment]
> This is caused by a feature in Huawei's device called **Power Genie**. It basically kill those application running in the background periodically to save battery life. They put a series of apps like Facebook, WeChat in the white list so that these apps will not be killed but MicroG is not in the list. There is no way to manually add an app to that list so far.
> 
> To solve your issue, you could uninstall the Power Genie on your Huawei P Smart. ([https://www.youtube.com/watch?v=2tfZmxqEnz4](url))
> 
> Don't worry about uninstalling this, I did that 6 months ago, it doesn't bring me any negative effects.

Thanks, i tought that Huawei P Smart 2021 doesn't have "Power Genie". I will try to uninstall.. Would battery optimizer still works without that? And Would  this have negative efects on updates?

**Comment by pkcheng** [comment]
It won't affect battery optimizer and system update. Initially, I plan to reinstall it if there is any negative effect, but I didn't do that till now because nothing bad happen and the notification works without shutting down.

You could refer to this link to uninstall and reinstall Power Genie.
[Link](https://forum.xda-developers.com/t/remove-powergenie-to-allow-background-apps-to-receive-push-notifications.3890409/)

**Comment by mire777** [comment]
> It won't affect battery optimizer and system update. Initially, I plan to reinstall it if there is any negative effect, but I didn't do that till now because nothing bad happen and the notification works without shutting down.
> 
> You could refer to this link to uninstall and reinstall Power Genie. [Link](https://forum.xda-developers.com/t/remove-powergenie-to-allow-background-apps-to-receive-push-notifications.3890409/)

Thank you, i will notify did I succeed, then we can close this..
