### ISSUE TITLE
com.deutschebahn.app.android (Next DB Navigator) crashes on open

### ISSUE THREAD

**Issue by 9Lukas5** [microg/GmsCore#1996]
**Affected app**
Name: Next DB Navigator
Package id: com.deutschebahn.app.android

**Describe the bug**
App won't start, immediately crashes on opening

**To Reproduce**
install and try to open

**Expected behavior**
App launches and works

**System**
Android Version: 13
Custom ROM: LineageOS 20

**microG**
microG Core version: 0.2.27.223616
microG Self-Check results: :white_check_mark: 

**Additional context**
Device runs LineageOS 20 with the MicroG patch for signature spoofing applied.
Therefore no PlayStore, Apk got sideloaded.

I opened this ticket, as I got told from someone else without Google Play Services AND without MicroG the Next Navigator works for that person.

[logcat-next-navigator-crash.log](https://github.com/microg/GmsCore/files/12207436/logcat-next-navigator-crash.log)

**Comment by tcecyk** [comment]
can you note down you db next app version?

Couldn't reproduce your error. I think it's due to my device having different dpi resolution - other xml nodes will be read for drawing layouts, with images + higher resolution, see this - https://stackoverflow.com/a/23202156/7010943

```
E AndroidRuntime: android.view.InflateException: Binary XML file line #132 in com.deutschebahn.app.android:layout/fragment_home: Binary XML file line #2 in com.deutschebahn.app.android:layout/view_blitzbox: Error inflating class
```

Can you freshly boot with lots of free memory and try to reproduce?

**db next**
Version: 4.19.0 (157)

**System**
Android Version: 10
Custom ROM: /e/ Q / Lineage 17.1

**microG**
microG Core version: 0.2.28.231657-17 (9645c3e)-noen
microG Self-Check results: All ticked

**Comment by ale5000-git** [comment]
@9Lukas5
Could you plese verify that the problem still persist in the [nightly build](https://microg.org/dl/core-nightly.apk)?

**Comment by 9Lukas5** [comment]
Oh my sorry. I just stumbled over these Android App Bundles it seems :monocle_face: 
I found another download where the apk is much bigger and this one works.

I'm really sorry.
