### ISSUE TITLE
Please add Pin Protocol support for Fido2

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#2044]
From GPS changelog:
`- [Phone] Adding Pin Protocol support for Fido2 on Android Platform.`

We need it also :-)

**Comment by ligniant** [comment]
Hi, everyone! This would be a great enhancement and a feature many people have been waiting for a long time to be integrated into original Google Play Services.  I hope it will be integrated to microg soon too – it would be great. This is a key-feature to get the secure two-factor authentication without different passwords for every service running and I hope many services will upgrade there offers for this feature soon.

So I fully agree with @ale5000-git – We need it also :-)

As @mar-v-in mentioned in 
https://github.com/microg/GmsCore/issues/849#issuecomment-1304210240
this feature have not been integrated earlier because it have not been part of original Play services – this is now different! And he also mentioned it „shouldn't be too hard“ – so I am confident :-)

**Comment by ale5000-git** [comment]
This was added with #2194
