### ISSUE TITLE
Lyft doesn't work even with the Playstore installed.

### ISSUE THREAD

**Issue by isthisme** [microg/GmsCore#207]
Hello.  I've attempted to use an alternative to Uber called Lyft.  However everytime I open Lyft I just get a message saying "Lyft is having a problem with the Google Play services." and then the app just closes.  I have the regular Phonesky playstore app installed along with MicroG.

**Comment by mar-v-in** [comment]
Lyft seems to depend on Google Wallet API which is not supported for now. I will try to add a dummy version so that Lyft continues to run (even though payments through Google Wallet will not be possible).

**Comment by isthisme** [comment]
Hey mar-v-in, this is offtopic but I want to continue helping by reporting applications that aren't working.  However I'm not a developer and it is a bit unclear to me how I can get debug logs and logcats of applications that are malfunctioning.  I want to make it easier on you by providing logs.  I think I need to use adb?

**Comment by Nutomic** [comment]
@isthisme [Here are instructions to install adb on Windows](http://www.howtogeek.com/125769/how-to-install-and-use-abd-the-android-debug-bridge-utility/). On Linux, you can just install it via package manager.

Once you have adb set up and your device connected, run the following command:`adb logcat -s *:E`. This will show errors from all apps.

**Comment by ShapeShifter499** [comment]
Hi,

I have this same exact issue "Lyft is having a problem with the Google Play services"   I tried updating to the latest nightly build of microG Services Core  0.2.4-28-g97f4c82

**Comment by mar-v-in** [comment]
Commit 83725f4 (0.2.4-30) fixed several issues that are related to Lyft, but I guess there will still be issues with Lyft's latest app as they use many new Maps API features and possibly Places API as well. But older app versions should work as of now without further problems. Please test and report back.

**Comment by ShapeShifter499** [comment]
I haven't tried requesting a ride BUT the app now loads and lets me log in without issue. Thanks for the update!

**Comment by bfwrtaglead** [comment]
If you're not using Lyft Line then you can use the mobile website to request rides. It's available at https://ride.lyft.com/. Lyft said they're going to add Line and you can check the status at https://help.lyft.com/hc/en-us/articles/229653987-Request-a-Ride-Using-Your-Browser. They have some really terrible JavaScript developers so you'll hit API rate limits, see excessive map refresh calls, and get crashes when html5 notifications are enabled.

I use Line so I have the app installed. I've been using it with microG Services Core 0.2.4-81-gb1e98ea and microG Services Framework Proxy 0.1.0 for months. It functions however there are two issues. First, the map view is jarbled and off-center so you have to ignore whatever it shows. Second, you can't type a pickup or destination address because of the way Lyft implemented the address lookup. However there are workarounds for this problem that I'll explain. Note that selecting your pickup location using GPS does work.

One method to specify an address for pickup or destination is to change either your home or work address in the mobile web interface, reload the app, then select it from the dropdown menu. But if you have the Google Maps app installed it's easier:
  1. Map out a route from your pickup to destination
  2. Select the ride hailing tab
  3. Select Lyft Line
  4. Click the Open in App button
The addresses will be filled in and you can request a ride.

**Comment by emacsomancer** [comment]
I haven't tried completing a call, but with microg I seem to be able to access most areas of the Lyft app, except for the Payments tab, which is just blank.  But if I initiate a Lyft call, I can see payment options I previously set up as options.

**Comment by Riamse** [comment]
@bfwrtaglead  Does this workaround work for non-shared rides? e.g. Lux

**Comment by Riamse** [comment]
@infinity0  Are you already logged in to the app? I'm having issues in #689

**Comment by infinity0** [comment]
Yes I'm already logged in. I can't remember how I did that now. Possibly I logged in in a different phone (that has the official Google Play Services) and then transferred the app data in `/data/user/0` over to the new phone, so it already contained the authentication cookies. (Some tips on how to do that is [here](https://infinity0.github.io/droid-hacks/misc/migrate/)).

**Comment by georgelemental** [comment]
Lyft works just fine with MicroG on my device, no issues. Maybe this issue can be closed?
