### ISSUE TITLE
[com.spotify.music] Spotify notification player not working

### ISSUE THREAD

**Issue by GioPan04** [microg/GmsCore#2118]
**Affected app**
Name: Spotify
Package id: com.spotify.music

**Describe the bug**
When the app is restarted the player in the notification area doesn't update any more. It will get stuck on a song played before and all attempts to click buttons on the player will do nothing. Even if the app is opened and a song is playing, the notification will not update. The only way to get the player work again is to force close the app and reopening it. 

**To Reproduce**
1. Force close the app
2. Open Spotify and play a song
3. Pause the song and close the app
4. The notification is now stuck

**Expected behavior**
The player should update and the buttons should work.

**Screenshots**
https://github.com/microg/GmsCore/assets/29762826/2614f0c5-303c-4965-b328-61a90d34c28d

**System**
Android Version: 13
Custom ROM: Lineage OS microG 20

**microG**
microG Core version: 0.2.27.223616
microG Self-Check results: All ticked

**Additional context**
This has been reported also on the [Spotify support page](https://community.spotify.com/t5/Android/Spotify-loses-registration-as-media-player-in-quick-settings/td-p/5656690) but they said that is a microG problem.

**Comment by GioPan04** [comment]
Just saw that a user reported that it's not using microG but is having the same error, but the other users in the page were all using microG and even the Spotify devs said is related to microG. Maybe that user is having another issue (?)

**Comment by IdmFoundInHim** [comment]
Just curious, when you say "force close" and "close," what do you mean? I did some testing since I have experienced this issue on LineageOS 20, and I found:
* Using home button (gesture) or back button (gesture) to exit Spotify does not produce the issue
* Using recents button (gesture) and removing Spotify from recents *reproduces the issue*
* From the settings app, using the force close option *does not* produce the issue and actually fixes it

I think this matches your experience. The same bug also occurs if Spotify is paused in the background too long (which happens more in everyday usage), but I have not pinpointed the exact conditions to reproduce that. Limiting background processes or destroying activities as soon as the user leaves them did not produce the bug (without removing Spotify from recents).

Regardless, I used `adb logcat | grep gms` and did not find any microG interaction while reproducing the bug. The media controls are part of Android Open Source Project. I do not think this is a bug in microG but either in Android Open Source, LineageOS and others, or Spotify.

**Comment by e-xception** [comment]
Can confirm I get this exact issue when I disable normal google play services (I don't have microG). Spotify notification returns to work normally when I reenable gps. I'm using an S21 Ultra and the issue only started when I updated from one UI 5.1 to android 14+one UI 6.0. 
Sorry to reopen a closed issue but any solution been found?

**Comment by ale5000-git** [comment]
@e-xception
If you don't have microG there isn't anything to report here.
This is the microG repo.
