### ISSUE TITLE
POST request `GetPoIntegrityTokenRequest` returns no `GetPoIntegrityTokenResponse` body  

### ISSUE THREAD

**Issue by oSumAtrIX** [microg/GmsCore#2253]
## About

With PR https://github.com/microg/GmsCore/pull/2129, PoToken (Proof of origin token) support has been introduced to MicroG GmsCore. Apps such as YouTube [rely on PoToken to complete API requests successfully](https://github.com/microg/GmsCore/issues/1870#issuecomment-2014132666). GmsCore implements a POST request and expects `GetPoIntegrityTokenResponse` to be sent back as the response, but the response body is empty: https://github.com/microg/GmsCore/issues/1870#issuecomment-2016294507. Therefore, apps such as [YouTube stop working](https://github.com/microg/GmsCore/issues/1870).

## Reproduction

1. Install MicroG GmsCore that has implemented PR https://github.com/microg/GmsCore/pull/2129
2. Install YouTube and login
3. Observe the logs:
	```
	03-23 02:34:34.418   907  3961 D ChimeraServiceProvider: serviceIntentCall: com.google.android.gms.potokens.service.START -> Intent { act=com.google.android.gms.potokens.service.START pkg=com.google.android.gms cmp=com.google.android.gms/org.microg.gms.potokens.PoTokensService }
	03-23 02:34:34.421   907   907 D PoTokens: onBind: Intent { act=com.google.android.gms.potokens.service.START pkg=com.google.android.gms cmp=com.google.android.gms/org.microg.gms.potokens.PoTokensService }
	03-23 02:34:34.447   907   991 D PoTokens: bound by: GetServiceRequest{serviceId=POTOKENS, gmsVersion=240204000, packageName='com.google.android.youtube', extras=Bundle[{}]}
	03-23 02:34:34.447   907   991 D PoTokens: PoTokensApiService handleServiceRequest
	03-23 02:34:34.492   907   991 D PoTokens: responseStatusToken packageName: com.google.android.youtube
	03-23 02:34:34.493   907   907 D PoTokens: responseStatusToken start
	03-23 02:34:34.493   907   907 D PoTokens: PoTokenHelper postPoTokenForGms start
	03-23 02:34:34.824   907   907 D PoTokens: PoTokenHelper postPoTokenForGms response: GetPoIntegrityTokenResponse{}
	03-23 02:34:34.824   907   907 D PoTokens: PoTokenHelper postPoTokenForGms end
	03-23 02:34:34.824   907   907 D PoTokens: responseStatusToken end
	```
5. Observe https://github.com/microg/GmsCore/issues/1870

## Expected behavior

When MicroG GmsCore makes the POST request `GetPoIntegrityTokenRequest`, `GetPoIntegrityTokenResponse` is sent back, the response body is not empty.

## Ideas to resolve this issue

- Possibly the request is done incorrectly, using a network debugger such as HttpToolkit (on a rooted device it requires no setup) can give insight on a correct request (Screenshots made after resetting GMS app data because it seems they cache the tokens):
  ![image](https://github.com/microg/GmsCore/assets/13122796/b3396c0c-1988-44c8-8ac0-0a144919776a)
  ![image](https://github.com/microg/GmsCore/assets/13122796/e0361a8f-fb9a-4e3d-a542-bb5724223cf1)

## Screenshots

A request made by MicroG GmsCore to get `GetPoIntegrityTokenResponse`.

![image](https://github.com/microg/GmsCore/assets/13122796/78a2114e-9371-49c3-81a0-acad9999878c)

A YouTube request with PoToken bytes from Google Services:

![image](https://github.com/microg/GmsCore/assets/13122796/491b3013-c44b-4e5c-be66-7cee7dcc9e70)

With MicroG GmsCore (What is seen here is an error message that is sent when requesting the PoIntegrityToken fails, there are multiple error messages present with different values, each for every kind of error in the app):

![image](https://github.com/microg/GmsCore/assets/13122796/97a9a2c3-fac5-4444-8260-7f941fa1bbc3)

## System

Android 14, MicroG GmsCore (verified being spoofed)

**Comment by mar-v-in** [comment]
The request is likely missing a result from DroidGuard, resulting in the server not providing a token. This will happen when device attestation / safetynet is turned off in microG settings or your device is not capable of executing DroidGuard.

DroidGuard and PoToken are mechanisms to detect non-official software, operating systems and devices. microG does include an implementation of them, but will not make efforts to ensure they will think they are running on an official system. It is up to others to do that if necessary. I just verified that on a device that passes SafetyNet, PoToken works as intended and YouTube can play videos just fine.

As this issue seems to be coming from the context of YouTube ReVanced, I'd like to remind that the main purpose of PoToken is to ban unofficial YouTube apps and their users. If you can't play videos in YouTube ReVanced, that means everything works as intended. YouTube ReVanced and ReVanced in general are not supported or endorsed by microG.

**Comment by swiftgeek** [comment]
Experiencing this issue without revanced, and this finally explains why I seem to get blocked.
For some reason combining microg with adaway/pihole breaks it for me (sometimes accidentally by using wrong hotspot), but I haven't found a reliable way to get it unstuck yet (or might be related to not passing CTS since few weeks now)

**Comment by oSumAtrIX** [comment]
@mar-v-in 

Could you elaborate on the primary use of PoToken to clarify the ambiguity in what you meant with:

- > PoToken are mechanisms to detect non-official software, operating systems and devices.
-  > main purpose of PoToken is to ban unofficial YouTube apps
