### ISSUE TITLE
"Ask before registering a new app for push notifications" dialog layout is broken

### ISSUE THREAD

**Issue by Wojtaz0w** [microg/GmsCore#2270]
**Describe the bug**
Dialog which pops up when an app wants to register for FCM service has its layout broken, it is very narrow. 

**To Reproduce**
1. Enable "ask before registering a new app to recieve push notifications"  
2. Trigger the pop-up
3. See how broken it is

**Expected behavior**
Dialog is wide (normally) like on v0.3.0 of microG.

**Screenshots**
![Screenshot_20240328-101009_microG Services.png](https://github.com/microg/GmsCore/assets/104674625/9b1c36b4-fafb-4446-94e8-518d5a7303b8)

![Screenshot_20240327-230343_Usługi microG.png](https://github.com/microg/GmsCore/assets/104674625/02857326-8007-4a41-9ec2-db9640de7f69)

![Screenshot_20240327-230350_Usługi microG.png](https://github.com/microg/GmsCore/assets/104674625/5c5e63f8-fa6a-4769-956a-1cd43c1bbed2)

**System**
Android Version: 14
Custom ROM: crDroid 10.1

**Additional context**
Only happens on microG 0.3.1

**Comment by Vavun** [comment]
I suspect there are common causes for this issue too https://github.com/microg/GmsCore/issues/2271
In a number of languages, words are longer on average and reading something becomes problematic

**Comment by mar-v-in** [comment]
This issue is caused by invalid use of dialogs in the updated material design UI toolkit and affects all languages the same (it's also broken in English).

The issue #2271 you mentioned is also related to the new UI toolkit, and beside one issue (that causes a part of the horizontal screen estate to be wasted) is specifically that preference titles are now expected to be single line. This is the case for every preference in the current version AOSP system settings as well. The longterm solution for this is to adjust preference titles to be shorter so it works for every language. AOSP has translator instructions with the respective strings to limit the number of characters, which may mean that translators need to find a different wording that fulfills the requirement, even if less accurate. So we need to do the same. For the specific screen in the screenshot, the preference's description (both title and summary) are not very good anyway and should be redone, there's already some changes there on master for 0.3.2, but definitely should be improved further.

**Comment by Vavun** [comment]
@mar-v-in, Ok I'll try to rephrase where possible.
Combined with getting rid of empty space on the left for items without icons it will be enough I hope.

However, I don't completely agree that all those strings must be single line (should be, but not must).
For example google, allows line breaks even in settings and its parts
<details>

![Screenshot_20240506-233256_Settings](https://github.com/microg/GmsCore/assets/31875619/d700d651-461c-4cc7-a51e-3678304e7a65)
![Screenshot_20240506-233108_Google Play services](https://github.com/microg/GmsCore/assets/31875619/b5b56fce-a594-4bbd-9ba2-fffcdaee0dbb)

</details>

I don't think it looks bad.
