### ISSUE TITLE
GmsCore on huawei

### ISSUE THREAD

**Issue by mikac97** [microg/GmsCore#2274]
When i try to login on my gmail account i got error to login and says try again later its every time same problem 
![434366018_292002483940926_5623358499452981734_n](https://github.com/microg/GmsCore/assets/165417948/cadcd71a-4454-4577-a2f5-acddd353a56d)

**Comment by Dasar2709** [comment]
![Screenshot_20240330_145518_app revanced android gms](https://github.com/microg/GmsCore/assets/165467146/f75d862b-4bc8-4e18-bc7a-55596c6954a4)

**Comment by joeltim** [comment]
Before I was able to bypass this using Vanced login, but with the new version I cannot. Revanced is the only way to watch YouTube on Huawei and have a decent experience; I hope this can be remedied.

**Comment by Dasar2709** [comment]
Please as soon as possible to solve it

**Comment by tmasixpence** [comment]
cant use ,old version is unusable,hope can fix it.

**Comment by Dasar2709** [comment]
My tablet is not running youtube old version now

**Comment by mar-v-in** [comment]
- If this is about (Re)Vanced, microG does not support it and them misleadingly using the name microG GmsCore for a modified app does not mean that this is the right bugtracker for it.
- Otherwise, microG does only support very few Huawei device models. If you installed microG from AppGallery (where it automatically filters supported devices) and it does not work for you, please report back with exact version of microG used, device model and OS version. If microG does not show up in AppGallery for you, you can try installing the -hw version of microG, but if it's not possible to check all boxes in microG Self-Check, it won't work correctly and there is nothing we can do about that (as it means that your OS is not supported by microG).

**Comment by mikac97** [comment]
Fixed :)

**Comment by Dasar2709** [comment]
device name: HUAWEI MATEPAD T8
MODEL NO: KOB2-W09
OS: Android 10, EMUI 10, no Google Play Services

**Comment by miltonTouchdown** [comment]
Hi!,
device name: HUAWEI Matepad pro
Model:MRX-W09
OS: Harmonyos 2.0.0

Thanks for your contribution
