### ISSUE TITLE
Can't sign in with a huawei device

### ISSUE THREAD

**Issue by Taro2007** [microg/GmsCore#2276]
Hello,
I've installed the newest version of microG with the "revanced manager" on my smartphone, because there was an issue with "revanced youtube" and since then I can't log in with my google-account.
is it because i'm using a huawei device (Mate40 Pro)?
on all other devices with google services works totally fine.
I've already reinstalled all apps, which were necessary for running, but still doesn't work.

![282660840-73a7f58e-e437-40a8-a035-1b4c501a11d0](https://github.com/microg/GmsCore/assets/165476892/178e8116-0904-4846-b13b-e67a040d78c2)

**Comment by Vavun** [comment]
@oSumAtrIX, for God's sake, rename your microG fork to something else. Two programs that look the same and have the same name confuse people.

**Comment by tmasixpence** [comment]
same... old version can't use ,latest version incompatible.

**Comment by Triangulix** [comment]
I experience the same on a Huawei MatePad T

**Comment by ellikss** [comment]
Delite all apps, clear Cash and install again.

**Comment by Taro2007** [comment]
> Delite all apps, clear Cash and install again.

Did that already, still the same issue 😅

**Comment by mar-v-in** [comment]
- If this is about (Re)Vanced, microG does not support it and them misleadingly using the name microG GmsCore for a modified app does not mean that this is the right bugtracker for it.
- Otherwise, microG does only support very few Huawei device models. If you installed microG from AppGallery (where it automatically filters supported devices) and it does not work for you, please report back with exact version of microG used, device model and OS version. If microG does not show up in AppGallery for you, you can try installing the -hw version of microG, but if it's not possible to check all boxes in microG Self-Check, it won't work correctly and there is nothing we can do about that (as it means that your OS is not supported by microG).
