### ISSUE TITLE
Testing the positon.xyz network location server - confusing

### ISSUE THREAD

**Issue by Sapiosenses** [microg/GmsCore#2422]
Trying to ascertain the quality of network geolocation results sourced from the "positon.xyz" URL that Marvin shared on 6/15 .
https://github.com/microg/GmsCore/issues/2237#issuecomment-2169261681

For both the devices I'm testing with, the microG utility is not showing any recent location requests from any of my geolocation apps with the exception of one maps app. Even though both SatStat and My Location report network location input with an estimated accuracy of 100m during the tests. 

The "Request from Mozilla" switches are turned off in the microG utility and WiFi/Bluetooth scanning is enabled in ROM settings. One device is on A10 and the other on A14, different ROMs.

Is there some document somewhere that clearly explains the various forms of geolocation inputs to android, and how they interact with microG to get that data to the apps?

Depending on the device and ROM, SatStat lists:

- GPS provider
- "Passive" provider
- Network provider
- Fused provider

The only app of all of these that shows as having made a location requestion to microG is Sygic.

- SatStat
- My Location
- Magic Earth
- Organic Maps
- AmiGo (TomTom)
- Sygic
- Offi (transit scheduler)

So are the rest all bypassing fused location/network location and somehow getting the network location information elsewhere, or is this a display bug in the microG utility, or ?

Thanks

**Comment by joelkoen** [comment]
The Request from Mozilla switch also toggles the custom server. You will need to enable that to use positon.xyz.

If this is turned off, your phone would likely be estimating a location using data it has passively collected, assuming you have Remember from GPS enabled in microG Location settings.

**Comment by dylangerdaly** [comment]
Is there a way to view/dump my passively collected location data? I'd like to see what it contains.

**Comment by mar-v-in** [comment]
> With this system, I cannot distinguish between a local cached address (like we used to get from the DejaVu or LocalNLP UNLP backends) and one coming from an external network source. (like we used to get from the other traditional UNLP backends like Apple, Mozilla, GSM, WiFi, Baidu etc)

I see the issue. We might want to add some debug UI to microG in the future to help with this case. This can't be at SatStat, because both data in the end appears as "network" location (also, in contrast to the previous system, microG wouldn't even do "live" requests if local data seems to be accurate enough)

If you want some additional data (though not the amount you seem to be looking for), you can use this command to dump some internal state from a connected machine:
```sh
adb shell dumpsys activity service location
```

> Lastly, I still don't know where the Fused provider comes into the picture. I saw this show up in the SatStat legend for one of my devices in the past (probably the A14 device) but as of today it's nowhere to be seen on the legend or map on any of them.

There's two ways to get Fused location on Android, one is through the Play Services API, which is implemented by microG, and one is as an additional location provider beside network. The latter is not yet supported by microG, but is what SatState uses. It's missing in microG partly because many non-Google custom Android OS currently ship with a (broken) implementation of it, that can cause conflicts. I'll have to investigate again in how far we can still provide this as well (as it would be good for FOSS apps if they could use it).
