### ISSUE TITLE
MicroG reports signature spoofing patch as absent, when it should be present

### ISSUE THREAD

**Issue by sobornostea** [microg/GmsCore#2499]
**Describe the bug**
Signature spoofing should be present on my ROM ([LineageOS for microG](https://lineage.microg.org/)) but microG reports it as absent. MicroG seems to work fine despite this ? 

**To Reproduce**
1. Go to 'microG settings'
2. Click 'Self-check'
3. Look at 'Signature Spoofing Support"
4. See that it says that my "ROM has no native support for signature spoofing [...]" 

**Expected behavior**
I'd expect only ticked boxes with "System has signature spoofing support", "System grants signature spoofing permission", "System spoofs signature"

It only shows "System spoofs signature" as ticked

**Screenshots**
![image](https://github.com/user-attachments/assets/db51c5df-d757-4a61-8589-41fbb2a29138)

**System**
Android Version: 14
Custom ROM: 21-20240709-microG-instantnoodle

**Comment by manuel-covas** [comment]
Hi, I too saw this bug when using the suggested version `0.2.27.223616` from the team's F-Droid repo.

The er

**Comment by manuel-covas** [comment]
Hi, what version of microG Services are you using? I too had this message when using the suggested version `0.2.27.223616` on the team's F-Droid repo.

I believe that since the checkbox is checked it means the selfcheck still passed even though the message is present.

For me it is no longer shown after updating to `0.3.2.240913`

![Screenshot_20240821-011108_microG Services](https://github.com/user-attachments/assets/55095c48-b595-4677-99a3-7b49746cc23b)

Also, LineageOS [now allows signature spoofing for microG](https://github.com/LineageOS/android_frameworks_base/commit/6b793fa98a40dd6c2d6eb02988161ed123439428) so no need to be using a fork for that.

**Comment by ale5000-git** [comment]
This problem was already fixed.
