### ISSUE TITLE
[net.roehl.roehlmobile] DynmamicLink.API Dependency - Does a workaround exist?

### ISSUE THREAD

**Issue by normanhh3** [microg/GmsCore#2544]
**Affected app**
Name: My Roehl
Package id: net.roehl.roehlmobile

**Describe the bug**
While starting the app with microG installed, there is a dependency on 

**To Reproduce**
1. Install apk
2. Start app
3. Observe error messages (see below)

**Expected behavior**
It appears that there may be other apps where the DynamicLinks API is not a show stopping issue based on reading a few of the Github issues mentioning the same error message.

**Screenshots**
Error Messages:
 ![image](https://github.com/user-attachments/assets/4dafeae1-0eb3-46eb-86b8-cacb5ace321c)
 ![image](https://github.com/user-attachments/assets/0c8ea406-6da6-44be-b15e-967275f3deaa)

Device Info HW Screenshots
![image](https://github.com/user-attachments/assets/9c321d1b-34c5-47fa-9800-1dafa66c90ad)

**System**
Android Version: 12

**microG**
microG Core version: 0.2.27.223616 [Installed from F-Droid using default installation location]
microG Self-Check results: [e.g. All ticked]

It is **unclear** whether Signature Spoofing is required to get the DynamicLink API to work and so that hill has not yet been climbed.

![image](https://github.com/user-attachments/assets/5939bbf6-50bf-4bee-83c5-e62a7781358c)

**Additional context**
As the developer of the entire system, we have the ability to change the kernel however it would need to change to support this provided the trade-offs are reasonable.

**Comment by mar-v-in** [comment]
Just a remark: The current version is [0.3.2.240913](https://github.com/microg/GmsCore/releases/tag/v0.3.2.240913). 0.2.27.223616 only remains the default on F-Droid due to a feature that got removed and not replaced yet with 0.2.28.

Now to your issue: Signature spoofing is required for most Play Services APIs, including DynamicLinks, would require signature spoofing to work with microG. For this you need to apply a patch to the AOSP source code like one from the examples at https://github.com/microg/patches.

**Comment by normanhh3** [comment]
Thanks @mar-v-in for the feedback on both items.  It does not sound like even upgrading to the actual latest version resolves the issues that arise due to the lack of SignatureSpoofing.

We'll investigate that further.
