### ISSUE TITLE
Poor map performance with many markers/layers

### ISSUE THREAD

**Issue by Bubu** [microg/GmsCore#969]
The map view in the [WeShare](https://play.google.com/store/apps/details?id=com.we.weshare) app is unusably slow to respond. It seems to do lot's of stuff in the UI thread.
On a phone with play services the app works fine.

So this is most likely some of the overlay things that are slow here. The map works fine until the car POIs are loaded then it stops responding to input after scroll/zoom for a couple of seconds.

![image](https://user-images.githubusercontent.com/105185/67854885-8a035200-fb11-11e9-95e6-caf3e4ea8e5f.png)

You can also watch the progress of the poi clustering algorithm... it takes a couple of seconds when there's a lot going on on the map :see_no_evil:

**Comment by Nesaijn** [comment]
Seems to be the same with the car2go app

**Comment by Bubu** [comment]
Working hypothesis from @mar-v-in:

> Too many map layers (one for every marker by default) slow down mapbox to a crawl. Could potentially be solved by merging same z-level markers into one layer.

**Comment by ildar** [comment]
Is https://github.com/mapbox/mapbox-gl-native/pull/2444 in the mapbox release that MicroG's using? Mapbox guys say it improves the performance.

**Comment by K3XRad** [comment]
I think it will be good to change the title of the issue to something like "Poor map performance in apps". Because this issue is not about only WeShare app anymore.

I have the same issue in EQInfo ( https://play.google.com/store/apps/details?id=de.gempa.android.eqinfo&hl=en_US&gl=US ).

When there is displayed not so much earthquakes, then performance is good. But with thousands of them map becomes slower. Especially when I'm changing its scale.
![Image_0](https://user-images.githubusercontent.com/92029674/136359428-797da59a-143c-452c-a9ef-73695746c7ee.jpg)
![Image_1](https://user-images.githubusercontent.com/92029674/136359481-e7b6fc98-d26c-4081-84c3-b6c7a186745a.jpg)

**Comment by mlell** [comment]
Still a problem in 2022. Car/Bike sharing apps like Jelbi (Berlin) or Lime are barely usable (Fairphone 3, Android 10, microG)
